import type { Metadata } from "next";
import { Rubik } from 'next/font/google';
import "./globals.css";
import { Header } from './components/layout/header'
import { Footer } from "./components/layout/footer";

const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div className="min-h-screen flex flex-col">
          <Header />
          <main className="pt-16">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
